# -*- coding: utf-8 -*-
"""[VN]Lab_7_7_Conditions and Branching.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RX2foTTSlXi2mchkDdQ5kHlNfM9G7Qhp

# Lab 7.7 Conditions and Branching

Thời lượng ước tính: **20** phút

## Mục tiêu

Sau khi hoàn thành lab này, bạn sẽ có thể:

-   Làm việc với các câu lệnh điều kiện trong Python gồm các toán tử và phân nhánh.

<h2>Mục lục</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#cond">Câu lệnh điều kiện</a>
            <ul>
                <li><a href="comp">Toán tử so sánh</a></li>
                <li><a href="branch">Phân nhánh</a></li>
                <li><a href="logic">Toán tử logic</a></li>
            </ul>
        </li>
        <li>
            <a href="#quiz">Quiz về Câu lệnh điều kiện</a>
        </li>
    </ul>

</div>

<hr>

<h2 id="cond">Câu lệnh điều kiện</h2>

<h3 id="comp">Toán tử so sánh</h3>

Các phép so sánh sẽ so sánh một số giá trị hoặc toán hạng và tạo ra giá trị Boolean dựa trên một số điều kiện. Khi so sánh hai giá trị, bạn có thể sử dụng các toán tử sau:
<ul>
    <li>bằng: <b>==</b></li>
    <li>không bằng: <b>!=</b></li>
    <li>lớn hơn: <b>></b></li>
    <li>nhỏ hơn: <b>&lt;</b></li>
    <li>lớn hơn hoặc bằng: <b>>=</b></li>
    <li>nhỏ hơn hoặc bằng: <b>&lt;=</b></li>
</ul>

Hãy gán giá trị 5 cho<code> a</code>. Sử dụng toán tử bằng được biểu thị bằng hai dấu <b> ==</b> để xem hai giá trị có bằng nhau hay không. Trường hợp dưới đây so sánh biến <code> a</code> với 6.
"""

# Condition Equal

a = 5
a == 6

"""Kết quả là <b>False</b>, vì 5 không bằng 6.

Hãy xem xét toán tử so sánh đẳng thức sau: <code> i > 5</code>. Nếu giá trị của toán hạng bên trái, trong trường hợp này là biến <b> i </b> lớn hơn giá trị của toán hạng bên phải, trong trường hợp này là 5, thì câu lệnh là <b> True </b>. Nếu không, câu lệnh là <b> False </b>. Nếu <b> i </b> bằng 6, vì 6 lớn hơn 5 nên kết quả là <b> True </b>.
"""

# Greater than Sign

i = 6
i > 5

"""Cho <code>i = 2</code>. Câu lệnh sẽ là false vì 2 không lớn hơn 5:

"""

# Greater than Sign

i = 2
i > 5

"""Hãy hiển thị một số giá trị cho <code> i</code> trong hình. Đặt các giá trị lớn hơn 5 bằng màu xanh lá cây và phần còn lại là màu đỏ. Phần màu xanh lá cây thể hiện điều kiện là **True**, màu đỏ nơi câu lệnh là **False**. Nếu giá trị của <code> i</code> là 2, chúng ta được **False** vì 2 nằm trong phần màu đỏ. Tương tự, nếu giá trị của <code> i</code> là 6, chúng ta sẽ được **True** vì điều kiện nằm trong phần màu xanh.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsGreater.gif" width="650" />

Thử bất đẳng thức sử dụng dấu chấm than đứng trước dấu bằng, nếu hai toán hạng không bằng nhau thì điều kiện trả về **True**. Ví dụ: điều kiện sau sẽ là **True** miễn là giá trị của <code> i</code> không bằng 6:
"""

# Inequality Sign

i = 2
i != 6

"""Khi <code>i</code> bằng 6, biểu thức bất đẳng thức sẽ cho  <b>False</b>. 

"""

# Inequality Sign

i = 6
i != 6

"""Xem dãy số bên dưới. Nếu điều kiện là **True**, các số tương ứng được đánh dấu màu xanh lá cây và nếu điều kiện là **False** thì số tương ứng được đánh dấu màu đỏ. Nếu chúng ta đặt <code> i</code> bằng 2 thì toán tử là true vì 2 nằm trong vùng màu xanh. Nếu đặt <code> i</code> bằng 6, ta được **False** vì điều kiện rơi vào phần màu đỏ.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsIneq.gif" width="650" />

Chúng ta có thể áp dụng các phương thức tương tự với string. Ví dụ, sử dụng một toán tử bằng ở hai chuỗi khác nhau. Vì các chuỗi không bằng nhau, ta được **False**.
"""

# Use Equality sign to compare the strings

"ACDC" == "Michael Jackson"

"""Nếu chúng ta sử dụng toán tử bất đẳng thức, đầu ra sẽ là **True** vì các string không bằng nhau."""

# Use Inequality sign to compare the strings

"ACDC" != "Michael Jackson"

"""Phép toán bất đẳng thức cũng được sử dụng để so sánh các chữ cái/từ/ký hiệu theo giá trị ASCII của các chữ cái. Giá trị thập phân được hiển thị trong bảng sau thể hiện thứ tự của ký tự:

Ví dụ: mã ASCII cho <b>!</b> là 33, trong khi mã ASCII cho <b> +</b> là 43. Do đó <b> +</b> lớn hơn <b>!</b> vì 43 lớn hơn 33.

Tương tự, giá trị <b>A</b> là 65, và giá trị <b>B</b> là 66 nên:
"""

# Compare characters

'B' > 'A'

"""Khi có nhiều chữ cái thì chữ đầu tiên được ưu tiên về thứ tự:"""

# Compare characters

'BA' > 'AB'

"""<b> Lưu ý</b>: Các chữ cái viết hoa có mã ASCII khác với các chữ viết thường, nghĩa là so sánh giữa các chữ cái trong Python có phân biệt chữ hoa chữ thường.

<h3 id="branch">Phân nhánh (Branching)</h3>

Phân nhánh cho phép chúng ta chạy các câu lệnh khác nhau cho các đầu vào khác nhau. Hãy xem mệnh đề **if** như một căn phòng bị khóa, nếu mệnh đề là **Đúng** thì chúng ta có thể vào phòng và chương trình của bạn sẽ chạy một số tác vụ được xác định sẵn, nhưng nếu mệnh đề **Sai**, chương trình sẽ bỏ qua tác vụ.

Ví dụ, hãy xét hình chữ nhật màu xanh đại diện cho một buổi hòa nhạc ACDC. Nếu người tham dự 18 tuổi trở lên, họ có thể tham gia buổi hòa nhạc ACDC. Nếu họ từ 18 tuổi trở xuống thì không thể tham gia buổi hòa nhạc.
  
Hãy sử dụng các câu lệnh điều kiện đã học trước đó vì các điều kiện cần được kiểm tra trong câu lệnh **if**. Cú pháp đơn giản là <code>if<i> mệnh đề điều kiện</i>:</code>, chứa từ <code> if</code>, bất kỳ mệnh đề điều kiện nào và dấu hai chấm ở cuối. Để bắt đầu các tác vụ, cần thực thi trong điều kiện này ở một dòng mới có thụt lề. Các dòng code sau dấu hai chấm và có thụt lề sẽ chỉ được thực thi khi mênh đề **if** là **True**. Các tác vụ sẽ kết thúc khi dòng code không thụt lề.

Trong trường hợp dưới đây, các tác vụ thực thi <code> print(“you can enter”)</code> chỉ xảy ra nếu biến <code>age</code> lớn hơn 18 là đúng vì dòng code này có thụt vào. Tuy nhiên, việc thực thi <code> print (“move on”)</code> sẽ không bị ảnh hưởng bởi câu lệnh if.
"""

# If statement example

age = 19
#age = 18

#expression that can be true or false
if age > 18:
    
    #within an indent, we have the expression that is run if the condition is true
    print("you can enter" )

#The statements after the if statement will run regardless if the condition is true or false 
print("move on")

"""<i> Hãy thử bỏ ghi chú biến độ tuổi </i>

Hãy sử dụng sơ đồ sau để minh họa quy trình. Ở phía bên trái, chúng ta thấy điều sẽ xảy ra khi điều kiện là <b>True</b>; người tham gia buổi hòa nhạc ACDC thể hiện code sau thụt lề đang được thực thi; sau đó chúng di chuyển. Ở phía bên phải, chúng ta thấy điều sẽ xảy ra khi điều kiện là <b>False</b>, người đó không được cấp quyền đi vào và di chuyển. Trong trường hợp này, đoạn code sau thụt lề không chạy, nhưng phần còn lại của các câu lệnh vẫn chạy.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsIf.gif" width="650" />

Câu lệnh <code> else</code> chạy một khối code nếu không có điều kiện nào là **True** trước câu lệnh <code> else </code> này. Hãy sử dụng ví dụ về buổi hòa nhạc ACDC một lần nữa. Nếu người tham dự 17 tuổi, họ không thể đến buổi hòa nhạc ACDC, nhưng họ có thể đến buổi hòa nhạc Meatloaf.
Cú pháp của câu lệnh <code>else</code> tương tự như cú pháp của câu lệnh <code> if</code>, là <code> else:</code>. Lưu ý rằng, không có mệnh đề điều kiện nào cho <code> else</code>.
Hãy thử thay đổi các giá trị của <code> age</code> để xem điều gì sẽ xảy ra:
"""

# Else statement example

age = 18
# age = 19

if age > 18:
    print("you can enter" )
else:
    print("go see Meat Loaf" )
    
print("move on")

"""Quá trình này được minh họa dưới đây, trong đó mỗi khả năng được thể hiện ở mỗi bên của hình ảnh. Bên trái là trường hợp tuổi 17, chúng ta đặt biến tuổi là 17, và điều này nghĩa là người tham dự sẽ tới buổi hòa nhạc Meatloaf. Phần bên phải hiển thị điều sẽ xảy ra khi người tham dự trên 18 tuổi, trong trường hợp này là 19 và người tham dự được đi vào vào buổi hòa nhạc.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsElse.gif" width="650" />

Câu lệnh <code> elif</code>, viết tắt của else if, cho phép chúng ta kiểm tra các điều kiện bổ sung nếu các câu lệnh điều kiện trước là <b>False</b>. Nếu điều kiện cho câu lệnh <code> elif</code> là <b> True</b>, các biểu thức thay thế sẽ được thực thi. Hãy xem ví dụ về buổi hòa nhạc, nếu người tham dự 18 tuổi, họ sẽ đến buổi hòa nhạc Pink Floyd thay vì buổi hòa nhạc ACDC hoặc Meat-loaf. Người 18 tuổi vào khu vực này, và vì họ không đủ 18 tuổi thì không thể xem ACDC, nhưng khi đủ 18 tuổi, họ tham dự Pink Floyd. Sau khi nhìn thấy Pink Floyd, họ tiếp tục. Cú pháp của câu lệnh <code> elif</code> tương tự ở chỗ chúng ta chỉ thay đổi <code> if</code> trong câu lệnh <code> if</code> thành <code> elif</code>.
"""

# Elif statment example

age = 18

if age > 18:
    print("you can enter" )
elif age == 18:
    print("go see Pink Floyd")
else:
    print("go see Meat Loaf" )
    
print("move on")

"""Ba kết hợp được hiển thị trong hình bên dưới. Phần bên trái cho biết điều gì sẽ xảy ra khi người tham dự dưới 18 tuổi. Phần ở giữa hiển thị khi người tham dự 18 tuối. Phần bên phải hiển thị khi người tham dự trên 18 tuổi.

<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsElif.gif" width="650" />

Hãy xem code sau:
"""

# Condition statement example

album_year = 1983
album_year = 1970

if album_year > 1980:
    print("Album year is greater than 1980")
    
print('do something..')

"""Hãy thay giá trị <code>album_year</code> thành các giá trị khác -- bạn sẽ thấy kết quả thay đổi!

Lưu ý rằng code trong khối <b> thụt lề </b> ở trên sẽ chỉ được thực thi nếu kết quả là <b>True</b>.

Như trước, chúng ta có thể thêm khối <code>else</code> vào khối <code>if</code>. Code trong khối <code>else</code> sẽ chỉ được thực thi nếu kết quả là <b>False</b>.

<b>Cú pháp:</b> 

if (điều kiện):

```
# do something
```

else:

```
# do something else
```

Nếu điều kiện trong câu lệnh <code> if</code> là <b> False</b>, câu lệnh sau khối <code> else</code> sẽ thực thi. Điều này được thể hiện trong hình:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsLogicMap.png" width="650" />
"""

# Condition statement example

album_year = 1983
#album_year = 1970

if album_year > 1980:
    print("Album year is greater than 1980")
else:
    print("less than 1980")

print('do something..')

"""Hãy thay đổi giá trị <code> album_year</code> thành các giá trị khác - bạn sẽ thấy rằng kết quả cũng thay đổi!

<h3 id="logic">Toán tử logic</h3>

Đôi khi bạn muốn kiểm tra nhiều điều kiện cùng một lúc. Ví dụ: bạn có thể muốn kiểm tra xem điều kiện này và điều kiện khác có phải là **True** hay không. Toán tử logic cho phép bạn kết hợp hoặc sửa đổi các điều kiện.

<ul>
    <li><code>and</code></li>
    <li><code>or</code></li>
    <li><code>not</code></li>
</ul>
 
Các toán tử này được tóm lược cho hai biến bằng cách sử dụng bảng sự chân lý (truth table) sau:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsTable.png" width="650" />

Câu lệnh <code>and</code> chỉ đúng khi cả hai điều kiện đều đúng. Câu lệnh <code>or</code> đúng nếu một điều kiện là đúng. Câu lệnh <code>not</code> xuất ra giá trị thật ngược lại.

Hãy xem cách xác định xem một album được phát hành sau năm 1979 (không bao gồm năm 1979) và trước năm 1990 (không bao gồm năm 1990). Khoảng thời gian từ 1980 đến 1989 thỏa mãn điều kiện này. Điều này được thể hiện trong hình bên dưới. Màu xanh trên các đường <strong> a </strong> và <strong> b </strong> biểu thị các khoảng thời gian mà câu lệnh là **True**. Màu xanh trên đường <strong> c </strong> biểu thị vị trí của cả hai điều kiện là **True**, điều này tương ứng với vị trí các vùng màu xanh chồng lên nhau.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsEgOne.png" width="650" />

Khối code thực hiện kiểm tra này được cung cấp bởi:
"""

# Condition statement example

album_year = 1980

if(album_year > 1979) and (album_year < 1990):
    print ("Album year was in between 1980 and 1989")
    
print("")
print("Do Stuff..")

"""Để xác định xem một album được phát hành trước năm 1980 (~ - 1979) hay sau năm 1989 (1990 - ~ ), có thể sử dụng câu lệnh **or**. Khoảng thời gian trước năm 1980 (~ - 1979) hoặc sau năm 1989 (1990 - ~) thỏa mãn điều kiện này. Điều này được thể hiện trong hình sau, màu xanh ở <strong> a </strong> và <strong> b </strong> thể hiện các khoảng thời gian mà câu lệnh là đúng. Màu xanh ở **c** thể hiện nơi có ít nhất một trong các điều kiện là đúng.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/CondsEgTwo.png" width="650" />

Khối code thực hiện kiểm tra này được cung cấp bởi:
"""

# Condition statement example

album_year = 1990

if(album_year < 1980) or (album_year > 1989):
    print ("Album was not made in the 1980's")
else:
    print("The Album was made in the 1980's ")

"""Câu lệnh <code>not</code> kiểm tra liệu câu lệnh có sai:

"""

# Condition statement example

album_year = 1983

if not (album_year == '1984'):
    print ("Album year is not 1984")

"""<hr>

<h2 id="quiz">Quiz về điều kiện</h2>

Viết câu lệnh if để xác định một album có xếp hạng lớn hơn 8. Kiểm tra bằng cách sử dụng xếp hạng cho album <b> “Back in Black” </b> có xếp hạng 8,5. Nếu câu lệnh là đúng, hãy in ra "This album is Amazing!"
"""

# Write your code below and press Shift+Enter to execute
rating_album = 8.5
if rating_album > 8:
  print('This album is Amazing!')

"""<details><summary>Bấm vào đây để xem đáp án</summary>

```python
rating = 8.5
if rating > 8:
    print ("This album is Amazing!")
```

</details>

<hr>

Viết một câu lệnh if-else thực hiện các thao tác sau. Nếu xếp hạng lớn hơn 8 thì in “this album is amazing”. Nếu xếp hạng nhỏ hơn hoặc bằng 8 thì in ra “this album is ok”.
"""

# Write your code below and press Shift+Enter to execute

if rating_album > 8:
  print('This album is Amazing!')
else:
  print('this album is ok')

"""<details><summary>Bấm vào đây để xem đáp án</summary>

```python
rating = 8.5
if rating > 8:
    print ("this album is amazing")
else:
    print ("this album is ok")
    
```

</details>

<hr>

Viết câu lệnh if để xác định xem album ra mắt trước năm 1980 hay vào những năm: 1991 hay 1993. Nếu điều kiện là đúng, hãy in ra năm album ra mắt.
"""

# Write your code below and press Shift+Enter to execute
if album_year < 1980 or album_year in [1991,1993]:
  print(album_year)

"""<details><summary>Bấm vào đây để xem đáp án</summary>

```python
album_year = 1979

if album_year < 1980 or album_year == 1991 or album_year == 1993:
    print ("This album came out in year %d" %album_year)
    
```

</details>

<hr>
Nguồn: IBM
<hr>
"""