# -*- coding: utf-8 -*-
"""[VN]Lab_7_4_Tuple trong Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L10bBENIyj-8499wt6wxMDU5RSQDGALD

# Lab 7.4 Tuple trong Python

Thời lượng ước tính: **15** phút

## Mục tiêu

Sau khi hoàn thành lab này, bạn sẽ có thể:

-   Thực hiện các thao tác cơ bản với tuple trong Python, gồm indexing (chỉ mục), slicing sorting (sắp xếp)

<h2>Mục lục</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#dataset">Về tập dữ liệu</a>
        </li>
        <li>
            <a href="#tuple">Tuple</a>
            <ul>
                <li><a href="index">Indexing</a></li>
                <li><a href="slice">Slicing</a></li>
                <li><a href="sort">Sorting</a></li>
            </ul>
        </li>
        <li>
            <a href="#escape">Quiz về Tuple</a>
        </li>
    </ul>
 
</div>

<hr>

<h2 id="dataset">Về tập dữ liệu</h2>

Hãy tưởng tượng bạn nhận được các đề xuất về album từ bạn bè và tổng hợp tất cả các đề xuất thành một bảng, với thông tin cụ thể về từng album.

Trong bảng, thông tin mỗi bộ phim nằm trong một hàng và các cột:

-   **artist** - Tên nghệ sĩ
-   **album** - Tên album
-   **released_year** - Năm phát hành album
-   **length_min_sec** - Độ dài album (giờ, phút, giây)
-   **genre** - Thể loại album
-   **music_recording_sales_millions** - Doanh thu đĩa nhạc (triệu USD) trên [SONG://DATABASE](http://www.song-database.com?cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork-19487395&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork-19487395&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork-19487395&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)
-   **claimed_sales_millions** - Doanh số đã tuyên bố của album (triệu USD) trên [SONG://DATABASE](http://www.song-database.com?cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork-19487395&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)
-   **date_released** - Ngày phát hành album
-   **soundtrack** - Cho biết album có phải là movie soundtrack (Y - Có) hay không (N - Không)
-   **rating_of_friends** - Cho biết xếp hạng từ bạn bè từ 1 tới 10
    <br>
    <br>

Có thể xem tập dữ liệu bên dưới:

<font size="1">
<table font-size:xx-small>
  <tr>
    <th>Artist</th>
    <th>Album</th> 
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th> 
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td> 
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td> 
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td> 
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td> 
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td> 
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td> 
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td> 
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td> 
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<hr>

<h2 id="tuple">Tuple</h2>

Trong Python có các kiểu dữ liệu khác nhau như: string (chuỗi), integer (số nguyên) và float (số thực). Tất cả các kiểu dữ liệu này có thể được chứa trong một tuple như sau:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesType.png" width="750" align="center" />

Bây giờ, hãy tạo tuple đầu tiên của bạn với string, integer và float.
"""

# Create your first tuple

tuple1 = ("disco",10,1.2 )
tuple1

"""Kiểu dữ liệu của biến là **tuple**. 

"""

# Print the type of the tuple you created

type(tuple1)

"""<h3 id="index">Indexing (Chỉ mục)</h3>

Mỗi phần tử của một tuple có thể được truy cập thông qua một chỉ mục. Bảng sau đây đại diện cho mối quan hệ giữa chỉ mục và các mục trong tuple. Mỗi phần tử có thể được lấy bằng tên của tuple theo sau bởi một dấu ngoặc vuông với số chỉ mục:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesIndex.gif" width="750" align="center">

Chúng ta có thể in ra từng giá trị trong tuple:
"""

# Print the variable on each index

print(tuple1[0])
print(tuple1[1])
print(tuple1[2])

"""Chúng ta có thể in ra **type (kiểu)** của từng giá trị trong tuple:

"""

# Print the type of value on each index

print(type(tuple1[0]))
print(type(tuple1[1]))
print(type(tuple1[2]))

"""Chúng ta cũng có thể sử dụng chỉ mục âm, sử dụng cùng bảng trên với các giá trị âm tương ứng:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesNeg.png" width="750" align="center">

Chúng ta có thể lấy phần tử cuối cùng như sau (lần này chúng ta sẽ không sử dụng câu lệnh print để hiển thị các giá trị):
"""

# Use negative index to get the value of the last element

tuple1[-1]

"""Chúng ta có thể hiển thị hai phần tử tiếp theo như sau:

"""

# Use negative index to get the value of the second last element

tuple1[-2]

# Use negative index to get the value of the third last element

tuple1[-3]

"""<h3 id="concate">Nối Tuple</h3>

Chúng ta có thể nối hoặc kết hợp các tuple sử dụng dấu **+**:
"""

# Concatenate two tuples

tuple2 = tuple1 + ("hard rock", 10)
tuple2

"""Chúng ta có thể chia nhỏ tuple, thu nhiều giá trị như được minh họa trong hình bên dưới:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesSlice.gif" width="750" align="center">

<h3 id="slice">Slicing</h3>

Chúng ta có thể chia nhỏ tuple, có các tuple mới với các phần tử tương ứng:
"""

# Slice from index 0 to index 2

tuple2[0:3]

"""Chúng ta có thể lấy hai phần tử cuối cùng của tuple:

"""

# Slice from index 3 to index 4

tuple2[-2:5]

"""Chúng ta có thể lấy độ dài của một tuple bằng cách sử dụng lệnh length:

"""

# Get the length of tuple

len(tuple2)

"""Hình này cho thấy số phần tử:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesElement.png" width="750" align="center">

<h3 id="sort">Sorting (Sắp xếp)</h3>

Xem xét tuple sau:
"""

# A sample tuple

Ratings = (0, 9, 6, 5, 10, 8, 9, 6, 2)

"""Chúng ta có thể sắp xếp các giá trị trong một tuple và lưu nó vào một tuple mới:

"""

# Sort the tuple

RatingsSorted = sorted(Ratings)
RatingsSorted

"""<h3 id="nest">Nested Tuple (Tuple lồng nhau)</h3>

Một tuple có thể chứa một tuple khác hay các kiểu dữ liệu phức tạp hơn. Quá trình này được gọi là 'nesting'. Hãy xem xét tuple sau với một số phần tử:
"""

# Create a nest tuple

NestedT =(1, 2, ("pop", "rock") ,(3,4),("disco",(1,2)))

"""Mỗi phần tử trong tuple bao gồm các tuple khác có thể được lấy thông qua một chỉ mục như trong hình:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesNestOne.png" width="750" align="center">
"""

# Print element on each index

print("Element 0 of Tuple: ", NestedT[0])
print("Element 1 of Tuple: ", NestedT[1])
print("Element 2 of Tuple: ", NestedT[2])
print("Element 3 of Tuple: ", NestedT[3])
print("Element 4 of Tuple: ", NestedT[4])

"""Chúng ta có thể sử dụng chỉ mục thứ hai để truy cập các tuple khác như  hình minh họa:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesNestTwo.png" width="750" align="center">

Chúng ta có thể truy cập nested tuple :
"""

# Print element on each index, including nest indexes

print("Element 2, 0 of Tuple: ",   NestedT[2][0])
print("Element 2, 1 of Tuple: ",   NestedT[2][1])
print("Element 3, 0 of Tuple: ",   NestedT[3][0])
print("Element 3, 1 of Tuple: ",   NestedT[3][1])
print("Element 4, 0 of Tuple: ",   NestedT[4][0])
print("Element 4, 1 of Tuple: ",   NestedT[4][1])

"""Chúng ta có thể truy cập các string trong nested tuple thứ hai sử dụng chỉ mục thứ ba:

"""

# Print the first element in the second nested tuples

NestedT[2][1][0]

# Print the second element in the second nested tuples

NestedT[2][1][1]

"""Chúng ta có thể hình dung quá trình này qua một cây. Mỗi chỉ mục mới tương ứng với một cấp độ sâu hơn ở cây:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesNestThree.gif" width="750" align="center">

Tương tự, chúng ta có thể truy cập các phần tử được lồng sâu hơn trong cây với chỉ mục thứ tư:
"""

# Print the first element in the second nested tuples

NestedT[4][1][0]

# Print the second element in the second nested tuples

NestedT[4][1][1]

"""Hình sau cho thấy mối quan hệ giữa cây và phần tử <code> NestedT[4][1][1]</code>:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesNestFour.gif" width="750" align="center">

<h2 id="quiz">Quiz về Tuple</h2>

Xem xét tuple sau:
"""

# sample tuple

genres_tuple = ("pop", "rock", "soul", "hard rock", "soft rock", \
                "R&B", "progressive rock", "disco") 
genres_tuple

"""Tìm độ dài của tuple, <code>genres_tuple</code>:

"""

# Write your code below and press Shift+Enter to execute
len(genres_tuple)

"""<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/TuplesQuiz.png" width="1100" align="center">

<details><summary>Bấm vào đây để xem đáp án</summary>

```python
len(genres_tuple)
```

</details>

Truy cập phần tử đối với chỉ mục 3:
"""

# Write your code below and press Shift+Enter to execute
genres_tuple [3][-1]

"""<details><summary>Bấm vào đây để xem đáp án</summary>

```python
genres_tuple[3]

```

</details>

Sử dụng slicing để lấy các chỉ mục 3, 4 và 5:
"""

# Write your code below and press Shift+Enter to execute
genres_tuple [3:6]

"""<details><summary>Bấm vào đây để xem đáp án</summary>

```python
genres_tuple[3:6]

```

</details>

Tìm hai phần tử đầu tiên của tuple <code>genres_tuple</code>:
"""

# Write your code below and press Shift+Enter to execute
genres_tuple [0:2]

"""<details><summary>Bấm vào đây để xem đáp án</summary>

```python
genres_tuple[0:2]

```

</details>

Tìm chỉ mục đầu tiên của <code>"disco"</code>:
"""

# Write your code below and press Shift+Enter to execute
genres_tuple.index("disco")

"""<details><summary>Bấm vào đây để xem đáp án</summary>

```python
genres_tuple.index("disco")

```

</details>

Tạo một danh sách được sắp xếp từ Tuple <code> C_tuple=(- 5, 1, -3)</code>:
"""

# Write your code below and press Shift+Enter to execute
C_tuple=(- 5, 1, -3)
sorted(C_tuple)

"""<details><summary>Bấm vào đây để xem đáp án</summary>

```python
C_tuple = (-5, 1, -3)
C_list = sorted(C_tuple)
C_list

```

</details>

<hr>
<p> Nguồn: IBM
<hr>
"""