# -*- coding: utf-8 -*-
"""[VN]Lab_7_2_Các thao tác với string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QIjmuum4k35nIiOT_ObORTVCVV6XqOVo

<h1>Lab 7.2 Các thao tác với string</h1>

Thời lượng ước tính: **15** phút

<p><strong>Xin chào!</strong> Notebook này sẽ dạy bạn về các thao tác với string (chuỗi) trong Ngôn ngữ lập trình Python. Ở phần cuối của notebook này, bạn sẽ biết các thao tác string cơ bản trong Python, bao gồm lập chỉ mục, escape sequence (dãy thoát) và các tác động đến string.</p>

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <a href="https://cocl.us/topNotebooksPython101Coursera">
         <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Ad/TopAd.png" width="750" align="center">
    </a>
</div>

<h2>Mục lục</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#strings">String là gì?</a>
        </li>
        <li>
            <a href="#index">Indexing (Chỉ mục)</a>
            <ul>
                <li><a href="neg">Chỉ mục âm</a></li>
                <li><a href="slice">Slicing</a></li>
                <li><a href="stride">Stride</a></li>
                <li><a href="concat">Nối String</a></li>
            </ul>
        </li>
        <li>
            <a href="#escape">Escape Sequence</a>
        </li>
        <li>
            <a href="#operations">Thao tác với String</a>
        </li>
        <li>
            <a href="#quiz">Quiz về Strings</a>
        </li>
    </ul>
    <p>
        Thời lượng ước tính: <strong>15 phút</strong>
    </p>
</div>

<hr>

<h2 id="strings">String là gì?</h2>

Ví dụ sau cho thấy một string chứa trong cặp dấu nháy kép:
"""

# Use quotation marks for defining string

"Michael Jackson"

"""Chúng ta cũng có thể sử dụng dấu nháy đơn:"""

# Use single quotation marks for defining string

'Michael Jackson'

"""String có thể là sự kết hợp của khoảng trắng và chữ số: """

# Digitals and spaces in string

'1 2 3 4 5 6 '

"""String cũng có thể là sự kết hợp của các ký tự đặc biệt: """

# Special characters in string

'@#2_#]&*^%$'

"""Chúng ta có thể in ra string sử dụng câu lệnh print:"""

# Print the string

print("hello!")

"""Chúng ta có thể liên kết hoặc gán string cho một biến khác:

"""

# Assign string to variable

Name = "Michael Jackson"
Name

"""<hr>

<h2 id="index">Chỉ mục</h2>

Sẽ rất hữu ích nếu coi string là một dãy có thứ tự. Mỗi phần tử trong dãy có thể được truy cập bằng cách sử dụng một chỉ số được biểu thị bằng mảng số:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsIndex.png" width="600" align="center" />

Chỉ mục đầu tiên có thể được truy cập như sau:

<hr/>
<div class="alert alert-success alertsuccess" style="margin-top: 20px">
[Tip]: Bởi vì chỉ mục bắt đầu từ 0, có nghĩa là chỉ mục đầu tiên nằm trên chỉ mục 0.
</div>
<hr/>
"""

# Print the first element in the string

print(Name[0])

"""Chúng ta có thể truy cập chỉ mục 6:"""

# Print the element on index 6 in the string

print(Name[6])

"""Hơn nữa, chúng ta có thể truy cập chỉ mục thứ 13:"""

# Print the element on the 13th index in the string

print(Name[13])

"""<h3 id="neg">Chỉ mục âm</h3>

Chúng ta có thể dùng chỉ mục âm với string:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsNeg.png" width="600" align="center" />

Chỉ mục âm có thể giúp chúng ta đếm phần tử từ cuối string.

Phần tử cuối cùng được cho bởi chỉ mục -1:
"""

# Print the last element in the string

print(Name[-1])

"""Phần tử đầu tiên có thể nhận được bằng chỉ mục -15:"""

# Print the first element in the string

print(Name[-15])

"""Chúng ta có thể tìm số ký tự trong một string bằng cách sử dụng <code>len</code>, viết tắt của length:"""

# Find the length of string

len("Michael Jackson")

"""<h3 id="slice">Slicing</h3>

Chúng ta có thể lấy nhiều ký tự từ một string bằng cách sử dụng slicing (lấy khoảng giá trị), chúng ta có thể lấy phần tử 0 đến 4 và 8 đến 12:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsSlice.png" width="600" align="center" />

<hr/>
<div class="alert alert-success alertsuccess" style="margin-top: 20px">
[Tip]: Khi lấy khoảng giá trị, số đầu tiên là chỉ mục (bắt đầu từ 0) và số thứ hai là độ dài từ chỉ mục đến phần tử cuối cùng bạn muốn (bắt đầu từ 1)
</div>
<hr/>
"""

# Take the slice on variable Name with only index 0 to index 3

Name[0:4]

# Take the slice on variable Name with only index 8 to index 11

Name[8:12]

"""<h3 id="stride">Stride</h3>

Chúng ta cũng có thể nhập giá trị stride như sau, với '2' cho biết rằng chúng ta đang chọn mọi biến thứ hai:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsStride.png" width="600" align="center" />
"""

# Get every second element. The elments on index 1, 3, 5 ...

Name[::2]

"""Chúng ta cũng có thể kết hợp slicing với stride. Trong trường hợp này, chúng ta chọn năm phần tử đầu tiên và sau đó sử dụng stride: """

# Get every second element in the range from index 0 to index 4

Name[0:5:2]

"""<h3 id="concat">Nối String</h3>

Chúng ta có thể nối hoặc kết hợp các string bằng cách sử dụng các ký hiệu cộng và kết quả được một string mới là sự kết hợp của cả hai:
"""

# Concatenate two strings

Statement = Name + "is the best"
Statement

"""Để sao chép các giá trị của một string, chúng ta chỉ cần nhân string với số lần chúng ta muốn sao chép nó. Trong trường hợp này là 3. Kết quả là một string mới, bao gồm 3 bản sao của string ban đầu:"""

# Print the string for 3 times

3 * "Michael Jackson"

"""Bạn có thể tạo một string mới bằng cách đặt nó thành biến ban đầu. Được nối với một string mới, kết quả là string mới thay đổi từ Michael Jackson thành "Michael Jackson is the best".

"""

# Concatenate strings

Name = "Michael Jackson"
Name = Name + " is the best"
Name

"""<hr>

<h2 id="escape">Escape Sequence</h2>

Dấu gạch chéo ngược biểu thị sự bắt đầu của escape sequence. Escape thể hiện rằng các string có thể khó nhập. Ví dụ, \n đại diện cho một dòng mới. Đầu ra được đưa ra bởi một dòng mới sau khi bắt gặp \n:
"""

# New line escape sequence

print(" Michael Jackson \n is the best" )

"""Tương tự, \t thể hiện một khoảng cách (tương tự tạo khoảng cách khi nhấn nút tab): """

# Tab escape sequence

print(" Michael Jackson \t is the best" )

"""Nếu bạn muốn đặt dấu gạch chéo ngược trong string của mình, hãy sử dụng dấu gạch chéo ngược kép:"""

# Include back slash in string

print(" Michael Jackson \\ is the best" )

"""Chúng ta cũng có thể đặt "r" trước string để hiển thị dấu gạch chéo ngược:"""

# r will tell python that string will be display as raw string

print(r" Michael Jackson \ is the best" )

"""<hr>

<h2 id="operations">Thao tác với String</h2>

Có nhiều phương thức thao tác string trong Python có thể sử dụng để thao tác dữ liệu. Chúng ta sẽ sử dụng một số thao tác string cơ bản trên dữ liệu.

Hãy thử phương thức <code>upper</code>; phương thức này chuyển đổi các ký tự chữ thường thành các ký tự viết hoa:
"""

# Convert all the characters in string to upper case

A = "Thriller is the sixth studio album"
print("before upper:", A)
B = A.upper()
print("After upper:", B)

"""Phương thức <code> replace</code> thay thế một phân đoạn của string, tức là thay một sub-string (chuỗi con) bằng một string mới. Chúng ta nhập phần của string muốn thay đổi. Đối số thứ hai là những gì chúng ta muốn trao đổi phân đoạn và kết quả được một string mới với phân đoạn đã thay đổi:

"""

# Replace the old substring with the new target substring is the segment has been found in the string

A = "Michael Jackson is the best"
B = A.replace('Michael', 'Janet')
B

"""Phương thức <code> find</code> tìm một sub-string. Đối số là sub-string bạn muốn tìm và đầu ra là chỉ mục đầu tiên của dãy. Chúng ta có thể tìm thấy sub-string <code> jack</code> hoặc <code> el</code>.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsFind.png" width="600" align="center" />
"""

# Find the substring in the string. Only the index of the first elment of substring in string will be the output

Name = "Michael Jackson"
Name.find('el')

# Find the substring in the string.

Name.find('Jack')

"""Nếu sub-string không nằm trong string thì kết quả đầu ra là phủ nhận. Ví dụ: string 'Jasdfasdasdf' không phải là sub-string:"""

# If cannot find the substring in the string

Name.find('Jasdfasdasdf')

"""<hr>

<h2 id="quiz">Quiz về String</h2>

Giá trị của biến <code>A</code> sau khi đoạn code sau được thực thi là bao nhiêu?
"""

# Write your code below and press Shift+Enter to execute 

A = "1"

"""Bấm vào <b>đây</b> để xem đáp án.

<!-- Your answer is below:
"1"
-->

Giá trị của biến <code>B</code> sau khi đoạn code sau được thực thi là bao nhiêu?
"""

# Write your code below and press Shift+Enter to execute

B = "2"

"""Bấm vào <b>đây</b> để xem đáp án.

<!-- Your answer is below:
"2"
-->

Giá trị của biến <code>C</code> sau khi đoạn code sau được thực thi là bao nhiêu?
"""

# Write your code below and press Shift+Enter to execute 

C = A + B
C

"""Bấm vào <b>đây</b> để xem đáp án.

<!-- Your answer is below:
"12"
-->

Hãy xem xét biến <code>D</code> sử dụng slicing để in ra ba phần tử đầu tiên:
"""

# Write your code below and press Shift+Enter to execute

D = "ABCDEFG"
D[0:3]

"""Bấm vào <b>đây</b> để xem đáp án.

<!-- Your answer is below:
print(D[:3]) 
# or 
print(D[0:3])
-->

Sử dụng giá trị stride là 2 để in ra mọi ký tự thứ hai của string <code> E</code>:
"""

# Write your code below and press Shift+Enter to execute

E = 'clocrkr1e1c1t'
E[::2]

"""Bấm vào <b>đây</b> để xem đáp án.

<!-- Your answer is below:
print(E[::2])
-->

<hr>

In ra dấu gạch chéo ngược:
"""

# Write your code below and press Shift+Enter to execute
print("\\")

"""Bấm vào <b>đây</b> để xem đáp án.
<!-- Your answer is below:
print("\\")
or
print(r" \ ")
-->

<hr>

Chuyển biến <code> F</code> thành chữ in hoa:
"""

# Write your code below and press Shift+Enter to execute

F = "You are wrong"
F.upper()

"""Bấm vào <b>đây</b> để xem đáp án.

<!-- Your answer is below:
F.upper()
-->

<hr>

Xem xét biến <code> G</code> và tìm chỉ mục đầu tiên của sub-string <code> snow</code>:
"""

# Write your code below and press Shift+Enter to execute

G = "Mary had a little lamb Little lamb, little lamb Mary had a little lamb \
Its fleece was white as snow And everywhere that Mary went Mary went, Mary went \
Everywhere that Mary went The lamb was sure to go"
G.find('snow')

"""Bấm vào <b>đây</b> để xem đáp án.

<!-- Your answer is below:
G.find("snow")
-->

Trong biến <code> G</code>, thay thế sub-string <code> Mary</code> bằng <code> Bob</code>:
"""

# Write your code below and press Shift+Enter to execute
G.replace('Mary', 'Bob')

"""Bấm vào <b>đây</b> để xem đáp án.

<!-- Your answer is below:
G.replace("Mary", "Bob")
-->

<hr>
<p>Nguồn: IBM
<hr>
"""