# -*- coding: utf-8 -*-
"""[VN]Lab_7_5_Dictionary trong Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SpA20qa9zebwB_gR6RAbergU6r2T0Kmj

# Lab 7.5 Dictionary trong Python

Thời lượng ước tính: **25** phút

## Mục tiêu

Sau khi hoàn thành lab này, bạn sẽ có thể:

-   Làm việc với các thư viện trong Python, gồm các thao tác

<h2>Mục lục</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>
            <a href="#dic">Dictionary</a>
            <ul>
                <li><a href="content">Dictionary là gì?</a></li>
                <li><a href="key">Key (Khóa)</a></li>
            </ul>
        </li>
        <li>
            <a href="#quiz">Quiz về Dictionary</a>
        </li>
    </ul>

</div>

<hr>

##<h2 id="Dic">Dictionary</h2>

##<h3 id="content">Dictionary là gì?</h3>

Dictionary chứa các khóa (key) và giá trị (value). Sẽ rất hữu ích nếu so sánh dictionary với list. Thay vì các chỉ mục số như list, dictionary có các khóa. Các khóa này được sử dụng để truy cập các giá trị trong dictionary.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/DictsList.png" width="650" />

Ví dụ về một Dictionary <code>Dict</code>:
"""

# Tạo dictionary

Dict = {"key1": 1, "key2": "2", "key3": [3, 3, 3], "key4": (4, 4, 4), ('key5'): 5, (0, 1): 6}
Dict

"""Các khóa có thể là string (chuỗi):

"""

# Truy cập giá trị bằng khóa

Dict["key1"]

"""Khóa cũng có thể là bất kỳ đối tượng bất biến nào, chẳng hạn như tuple:

"""

# Truy cập giá trị bằng khóa

Dict[(0, 1)]

"""Mỗi khóa được phân tách khỏi giá trị của nó bằng dấu hai chấm "<code>:</code>". Dấu phẩy phân tách các mục và toàn bộ dictionary được đặt trong dấu ngoặc nhọn. Một dictionary trống không có bất kỳ mục nào được viết chỉ bằng cặp dấu ngoặc nhọn như thế này "<code>{}</code>"."""

# Tạo dictionary mẫu

release_year_dict = {"Thriller": "1982", "Back in Black": "1980", \
                    "The Dark Side of the Moon": "1973", "The Bodyguard": "1992", \
                    "Bat Out of Hell": "1977", "Their Greatest Hits (1971-1975)": "1976", \
                    "Saturday Night Fever": "1977", "Rumours": "1977"}
release_year_dict

"""Tóm lại, giống như list, dictionary chứa một dãy các phần tử. Mỗi phần tử được thể hiện bằng một khóa và giá trị tương ứng. Dictionary được tạo bằng cặp dấu ngoặc nhọn chứa các khóa và giá trị được phân tách bằng dấu hai chấm. Mỗi khóa chỉ có thể có một giá trị duy nhất, tuy nhiên, nhiều khóa có thể chứa cùng một giá trị. Khóa chỉ có thể là chuỗi, số hoặc tuple, nhưng giá trị lại có thể là bất kỳ kiểu dữ liệu nào.

Sẽ rất hữu ích nếu hình dung từ điển dưới dạng bảng, như hình ảnh sau đây. Cột đầu tiên thể hiện các khóa, cột thứ hai thể hiện các giá trị.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/DictsStructure.png" width="650" />

##<h3 id="key">Khóa (Key)</h3>

Bạn có thể truy xuất các giá trị theo tên:
"""

# Lấy giá trị theo khóa

release_year_dict['Thriller']

"""Điều này tương ứng với:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/DictsKeyOne.png" width="500" />

Tương tự cho <b>The Bodyguard</b>
"""

# Lấy giá trị theo khóa

release_year_dict['The Bodyguard']

"""<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/DictsKeyTwo.png" width="500" />

Bây giờ chúng ta hãy truy xuất các khóa của dictionary bằng phương thức <code>keys()</code>:
"""

# Lấy tất cả các khóa trong dictionary

release_year_dict.keys()

"""Bạn có thể truy xuất các giá trị bằng phương thức  <code>values()</code>:

"""

# Lấy tất cả các giá trị trong dictionary

release_year_dict.values()

"""Chúng ta có thể thêm một mục:

"""

# Nối giá trị với khóa vào dictionary

release_year_dict['Graduation'] = '2007'
release_year_dict

"""Chúng ta có thể xóa một mục:   

"""

# Xóa mục theo khóa

del(release_year_dict['Thriller'])
del(release_year_dict['Graduation'])
release_year_dict

"""Bạn có thể xác minh xem liệu một phần tử có trong dictionary không: 

"""

# Xác minh xem khóa có trong dictionary không

'The Bodyguard' in release_year_dict

"""<hr>

##<h2 id="quiz">Quiz về Dictionary</h2>

<b> Bạn sẽ cần dictionary này cho hai câu hỏi tới:</b>
"""

# Dictionary mẫu câu hỏi

soundtrack_dic = {"The Bodyguard":"1992", "Saturday Night Fever":"1977"}
soundtrack_dic

"""a) Các khóa trong dictionary <code>soundtrack_dic</code> là?

"""

# Viết code của bạn xuống dưới và nhấn Shift+Enter để thực hiện
soundtrack_dic.keys()

"""<details><summary>Click vào đây để xem lời giải</summary>

```python
soundtrack_dic.keys() # The Keys "The Bodyguard" and "Saturday Night Fever" 

```

</details>

b) Các giá trị dictionary <code>soundtrack_dic</code> là?
"""

# Viết code của bạn xuống dưới và nhấn Shift+Enter để thực hiện
soundtrack_dic.values()

"""<details><summary>Click vào đây để xem lời giải</summary>

```python
soundtrack_dic.values() # The values are "1992" and "1977"

```

</details>

<hr>

<b> Bạn sẽ cần dictionary này cho hai câu hỏi tới:</b>

Các album <b> Back in Black </b>, <b> The Bodyguard </b> và <b> Thriller </b> có doanh số bán đĩa nhạc lần lượt là 50, 50 và 65 triệu:

a) Tạo dictionary <code>album_sales_dict</code> trong đó các khóa là tên album và giá trị là doanh số (triệu USD).
"""

# Viết code của bạn xuống dưới và nhấn Shift+Enter để thực hiện
album_sales_dict= { 'Back in Black': 50, 'The Bodyguard': 50, 'Thriller': 65}

"""<details><summary>Click vào đây để xem lời giải</summary>

```python
album_sales_dict = {"The Bodyguard":50, "Back in Black":50, "Thriller":65}

```

</details>

b) Dùng dictionary để tìm tổng doanh thu của album <b>Thriller</b>:
"""

# Viết code của bạn xuống dưới và nhấn Shift+Enter để thực hiện
album_sales_dict['Thriller']

"""<details><summary>Click vào đây để xem lời giải</summary>

```python
album_sales_dict["Thriller"]

```

</details>

c) Tìm tên các album từ dictionary dùng phương thức <code>keys()</code>:
"""

# Viết code của bạn xuống dưới và nhấn Shift+Enter để thực hiện
album_sales_dict.keys()

"""<details><summary>Click vào đây để xem lời giải</summary>

```python
album_sales_dict.keys()

```

</details>

d) Tìm giá trị của doanh thu đĩa nhạc từ dictionary sử dụng phương thức <code>values</code>:
"""

# Viết code của bạn xuống dưới và nhấn Shift+Enter để thực hiện
album_sales_dict.values()

"""<details><summary>Click vào đây để xem lời giải</summary>

```python
album_sales_dict.values()

```

</details>

<hr>
<p> Nguồn: IBM
<hr>
"""